version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - django
  
  django:
    build:
      context: .
      dockerfile: ./dockers/python/Dockerfile
    volumes:
      - ./source:/source
    command:
      gunicorn --chdir ./server startproject.wsgi -b 0.0.0.0:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=toor
    - POSTGRES_DB=jogos
    ports:
    - "5432:5432"